### 퀴즈 풀기
POST http://{{host}}/api/v1/quiz/2/answers
Content-Type: application/json
x-wequiz-token: your_token_value2

{
  "answers": [
    {
      "questionId": 3,
      "optionIds": [
        9
      ]
    },
    {
      "questionId": 4,
      "optionIds": [
        10
      ]
    }
  ]
}