### 퀴즈 풀기
POST http://{{host}}/api/v1/quiz/1/answers
Content-Type: application/json
x-wequiz-token: your_token_value

{
  "answers": [
    {
      "questionId": 1,
      "optionIds": [
        2
      ]
    },
    {
      "questionId": 2,
      "optionIds": [
        4
      ]
    }
  ]
}