### 회원 가입
POST http://{{host}}/api/v1/user/join
Content-Type: application/json
x-wequiz-token: your_token_value

{
  "token": "your_token_value",
  "phone": "your_phone_number",
  "nickname": "your_nickname",
  "description": "your_description"
}

### 내 정보 불러오기
GET http://{{host}}/api/v1/user
Content-Type: application/json
x-wequiz-token: your_token_value